### ISSUE TITLE
Installed extension, nothing happens loading a graphql document

### ISSUE THREAD

**Issue by oising** [radiy/vs-graphql-textmate#1]
I installed 1.2 -- you mention that it needs a `.graphqlrc.yml` file and your example file points at a schema -- but what if I'm writing a schema? Is this only for writing queries/mutations? Any other tips?

**Comment by radiy** [comment]
Can you please describe your use case. You are working on schema, so you are writing graphql server?
Extension is mostly for writing queries\mutations, for schema only colorization will work.
I think it`s maybe possible to make syntax check works for schema.

**Comment by oising** [comment]
Yes, im sorry for not being more specific. I'm building a server but using
a schema first approach, so I'm writing SDL by hand.

**Comment by radiy** [comment]
@oising I done some good, improved schema colorization.
![image](https://user-images.githubusercontent.com/341043/109349066-69264a80-7886-11eb-8d33-2bcde6ecb683.png)

**Comment by sungam3r** [comment]
@oising  Try v1.4

**Comment by oising** [comment]
I tried it, I see there's colour now (nice) but it seems the language server is crashing because there is no intellisense (intelligent completion.) It's still expecting to find a config file? If I'm only creating a schema file, what should be in the config file? Perhaps you should generate an empty/compliant/default config in the current folder ? 
 
```text
GraphQL Server initialization failed.StreamJsonRpc.RemoteInvocationException: Request initialize failed with message: GraphQL Config file is not available in the provided config directory: C:\p\hilo\Scratch\gql_schemafirst\gqlserver\
Please check the config directory.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__133`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by oising** [comment]
(there's nothing in the activitylog related to graphql -- the exception above I found in the Output for your extension)

![image](https://user-images.githubusercontent.com/1844001/109530004-3fd30d80-7a84-11eb-972c-29a3c7d823ea.png)
