### ISSUE TITLE
Development assistance

### ISSUE THREAD

**Issue by sungam3r** [radiy/vs-graphql-textmate#3]
Hi. This is the only VS extension I've found. I saw these only for VS Code. I'm glad that someone decided to write this for VS. I offer you my help in this. I have never written extensions for VS, but I have been working with GraphQL for quite some time now and support a number of projects related to it. See, for example, [GraphQL.NET](https://github.com/graphql-dotnet/graphql-dotnet), [Parser](https://github.com/graphql-dotnet/parser) or [Server](https://github.com/graphql-dotnet/server). The lack of support for GraphqL syntax in VS has seemed to me like nonsense for a long time. I will be glad to help.

**Comment by radiy** [comment]
I will be glad for any help. Biggest issue for me is a language server that requires configuration to work properly, if configuration absents LSP fails with an unhelpful message. It would be nice to teach lsp some good manners, at least show some actionable message instead of a scary error.

My current thinking is to provide a dummy LSP server that does nothing and just prints error message. Current lsp initialization code is here - https://github.com/radiy/vs-graphql-textmate/blob/312858abe266ad3aaab1d5ebcdebf635672eca5d/GraphQL/GQLLanguageService.cs#L117.

**Comment by sungam3r** [comment]
I see that in GraphQL Language Extension output:
```
GraphQL Server initialization failed.System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GraphQL.GQLLanguageService.<ActivateAsync>d__19.MoveNext()GraphQL Server initialization failed.System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GraphQL.GQLLanguageService.<ActivateAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by radiy** [comment]
Nodejs is required to run lsp server, it looks like it is not installed on your system.

**Comment by sungam3r** [comment]
Maybe. But I would like to know about it in an understandable way and certainly not from the error message in output window.

**Comment by radiy** [comment]
Agreed, current UX is horrible, need to figure out way to make it better.

**Comment by sungam3r** [comment]
Extension may require installation of necessary services?

**Comment by radiy** [comment]
Maybe, do not know for sure.
There are "Dependencies" block in vsixmanifest, https://github.com/radiy/vs-graphql-textmate/blob/0a174b01a58bed970ba33a8393a900de2445b5e5/GraphQL/source.extension.vsixmanifest#L11
It may be possible to specify nodejs as dependency, but I wouldn`t try too hard.

**Comment by sungam3r** [comment]
At least there should be a check for the existence of a file with a detailed error message in `GQLLanguageService`.
